CREATE TABLE TorqueRecord (
  Id INT NOT NULL IDENTITY(1,1),
  MotorQr VARCHAR(100) NOT NULL,
  TorqueValue FLOAT NOT NULL,
  IsQualified BIT NOT NULL,
  Time DATETIME NOT NULL,
  PRIMARY KEY (Id)
) 
