CREATE TABLE IF NOT EXISTS TorqueRecord (
  Id INT NOT NULL AUTO_INCREMENT,
  MotorQr VARCHAR(100) NOT NULL,
  TorqueValue DOUBLE NOT NULL,
  IsQualified TINYINT(1) NOT NULL,
  Time DATETIME NOT NULL,
  PRIMARY KEY (Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
